# Generated by Django 4.0.5 on 2022-07-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBrands',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ap_name', models.CharField(max_length=100)),
                ('ap_price', models.CharField(max_length=100)),
                ('ap_details', models.CharField(max_length=100)),
                ('ap_image', models.CharField(default='', max_length=400)),
                ('ap_description', models.CharField(max_length=100)),
                ('ap_status', models.IntegerField(default=0)),
                ('ap_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
