# Generated by Django 4.0.5 on 2022-07-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_addbrands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbrands',
            name='ap_description',
        ),
    ]
