# Generated by Django 4.0.5 on 2022-07-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_addvendors'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBike',
            fields=[
                ('ab_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ab_name', models.CharField(max_length=100)),
                ('ab_price', models.CharField(max_length=100)),
                ('ab_details', models.CharField(max_length=100)),
                ('ab_image', models.CharField(default='', max_length=400)),
                ('ab_status', models.IntegerField(default=0)),
                ('ab_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
