# Generated by Django 4.0.5 on 2022-07-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_addbike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('rg_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rg_name', models.CharField(max_length=100)),
                ('rg_mobile', models.CharField(max_length=100)),
                ('rg_email', models.CharField(max_length=100)),
                ('rg_password', models.CharField(max_length=100)),
                ('rg_address', models.CharField(default='', max_length=100)),
                ('rg_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='addbike',
            name='ab_image',
            field=models.ImageField(upload_to='app/static/media/bike/'),
        ),
        migrations.AlterField(
            model_name='addbrands',
            name='ap_image',
            field=models.ImageField(upload_to='app/static/media/brand/'),
        ),
    ]
