# Generated by Django 4.0.5 on 2022-07-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_register_alter_addbike_ab_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='rg_status',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
