# Generated by Django 4.0.5 on 2022-07-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_register_rg_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('or_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('or_name', models.CharField(max_length=100)),
                ('or_total_amount', models.CharField(max_length=100)),
                ('or_address', models.CharField(max_length=100)),
                ('or_ordered_by', models.CharField(max_length=100)),
                ('or_transaction_id', models.CharField(max_length=100)),
                ('or_status', models.CharField(default=0, max_length=100)),
                ('or_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
