# Generated by Django 4.2.3 on 2023-08-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPG',
            fields=[
                ('ab_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ab_name', models.CharField(max_length=100)),
                ('ab_price', models.CharField(max_length=100)),
                ('ab_details', models.CharField(max_length=100)),
                ('ab_address', models.CharField(max_length=100)),
                ('ab_image', models.ImageField(upload_to='app/static/media/pg/')),
                ('ab_status', models.IntegerField(default=0)),
                ('ab_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AddBike',
        ),
        migrations.DeleteModel(
            name='AddBrands',
        ),
    ]
