# Generated by Django 4.2.3 on 2023-08-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_addpg_delete_addbike_delete_addbrands'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpg',
            name='ab_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='addpg',
            name='ab_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
