# Generated by Django 4.2.3 on 2023-08-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_addpg_ab_location_alter_addpg_ab_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpg',
            name='ab_location',
            field=models.TextField(default='', max_length=100),
        ),
    ]
