# Generated by Django 4.2.3 on 2023-08-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_addpg_ab_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ct_name', models.CharField(max_length=100)),
                ('ct_mobile', models.CharField(max_length=100)),
                ('ct_email', models.CharField(max_length=100)),
                ('ct_subject', models.CharField(max_length=100)),
                ('ct_message', models.CharField(default='', max_length=100)),
                ('ct_status', models.CharField(default='0', max_length=100)),
            ],
        ),
    ]
