# Generated by Django 4.2.3 on 2023-08-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rv_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rv_name', models.CharField(max_length=100)),
                ('rv_mobile', models.CharField(max_length=100)),
                ('rv_email', models.CharField(max_length=100)),
                ('rv_review', models.CharField(default='', max_length=100)),
                ('rv_status', models.CharField(default='0', max_length=100)),
            ],
        ),
    ]
